chore: update scripts for initializing evm rollapp
dymensionxyz/rollapp-evm pull request #127
Opened 2024-03-28 14:40 UTC by artemijspavlovs

chore: add scripts to generate denom metadata, genesis accounts and update the genesis file
docs: README, add steps for denommetadata
docs: README, add steps for adding genesis accounts

## Description

----

Closes #XXX

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

2024-03-28 18:39 UTC, mtsitrin requested changes

2024-03-28 18:39 UTC, mtsitrin commented on README.md
> +dymd tx bank send local-user $SEQUENCER_ADDR 1000dym --keyring-backend test --broadcast-mode block --fees 1dym -b block -y --node ${HUB_RPC_URL}
redundent `--broadcast-mode block`

2024-03-28 18:39 UTC, mtsitrin commented on README.md
I don't think that all the "advanced" features, and those aimed for permission deployment should be part of the main readme.

IMO all the denom metadata, genesis accounts, vesting , should be at separate md file

2024-03-28 18:39 UTC, mtsitrin commented on scripts/settlement/add_genesis_accounts.sh
> +      "address": "$(dymd keys show bob-genesis --keyring-backend test --output json | jq -r .address)"
u can do `keys show -a` for address

2024-03-28 18:39 UTC, mtsitrin commented on scripts/settlement/register_sequencer_to_hub.sh
> +BOND_AMOUNT="100000dym"
it's too high bond, more that u fund the sequencer in the readme.
u can use the default gensis value for `min_bond`

2024-03-29 08:00 UTC, artemijspavlovs commented on README.md
I aggree, will create a separate README and revert the original one.

2024-04-02 16:39 UTC, omritoptix submitted a review, later dismissed

2024-04-02 16:41 UTC, merged